version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE=http://localhost:4000
    volumes:
      - ./frontend:/app
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "4000:4000"
    environment:
      - JWT_SECRET=${JWT_SECRET:-devsecret}
      - GROQ_API_KEY=${GROQ_API_KEY:-}
    volumes:
      - ./uploads:/app/uploads
      - ./worker:/app/worker
    depends_on:
      - worker

  worker:
    build: ./worker
    volumes:
      - ./uploads:/app/uploads
      - ./worker:/app/worker
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-}
